import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function DownloadReport({ reportData = [] }) {
  const handleDownloadPDF = () => {
    if (!reportData.length) {
      return;
    }

    const doc = new jsPDF();

    // -------------------------
    // Header
    // -------------------------

    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("ExpenseTracker", 20, 25);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Personal Finance", 20, 32);

    // -------------------------
    // Report title
    // -------------------------

    const currentDate = new Date();

    const month = currentDate.toLocaleString("en-US", {
      month: "long",
    });

    const year = currentDate.getFullYear();

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Monthly Expense Report", 20, 50);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`${month} ${year}`, 20, 58);

    // -------------------------
    // Calculate total
    // -------------------------

    const totalExpenses = reportData.reduce(
      (total, expense) => total + Number(expense.amount || 0),
      0,
    );

    const formattedTotal = totalExpenses.toLocaleString("en-IN", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });

    // -------------------------
    // Summary
    // -------------------------

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");

    doc.text(`Total Expenses: Rs. ${formattedTotal}`, 20, 75);

    doc.text(`Transactions: ${reportData.length}`, 20, 83);

    // -------------------------
    // Table
    // -------------------------

    const tableData = reportData.map((expense) => {
      const amount = Number(expense.amount || 0);

      return [
        expense.createdAt
          ? new Date(expense.createdAt).toLocaleDateString()
          : "-",

        expense.description || "-",

        expense.category || "-",

        expense.note || "-",

        `Rs. ${amount.toLocaleString("en-IN", {
          minimumFractionDigits: 2,
          maximumFractionDigits: 2,
        })}`,
      ];
    });

    autoTable(doc, {
      startY: 95,

      margin: {
        left: 15,
        right: 15,
      },

      head: [["Date", "Description", "Category", "Note", "Amount"]],

      body: tableData,

      theme: "grid",

      styles: {
        font: "helvetica",
        fontSize: 9,
        cellPadding: 4,
        overflow: "linebreak",
        valign: "middle",
      },

      headStyles: {
        fillColor: [16, 185, 129],
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },

      columnStyles: {
        0: {
          cellWidth: 25,
        },

        1: {
          cellWidth: 35,
        },

        2: {
          cellWidth: 30,
        },

        3: {
          cellWidth: 65,
        },

        4: {
          cellWidth: 35,
          halign: "right",
        },
      },
    });

    // -------------------------
    // Footer
    // -------------------------

    const pageHeight = doc.internal.pageSize.height;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");

    doc.text("Generated by ExpenseTracker", 20, pageHeight - 15);

    // -------------------------
    // Download
    // -------------------------

    doc.save(`expense-report-${month.toLowerCase()}-${year}.pdf`);
  };
  return (
    <div className="rounded-3xl border border-zinc-800 bg-zinc-900 p-8">
      <h2 className="text-2xl font-semibold text-white">Download Report</h2>

      <p className="mt-2 text-zinc-400">Export your expenses as CSV or PDF.</p>

      <div className="mt-8 flex gap-4">
        <button
          type="button"
          onClick={handleDownloadPDF}
          disabled={!reportData.length}
          className="rounded-xl bg-emerald-500 px-6 py-3 font-semibold text-white transition hover:bg-emerald-600 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Download CSV
        </button>

        <button
          type="button"
          onClick={handleDownloadPDF}
          disabled={!reportData.length}
          className="rounded-xl border border-zinc-700 px-6 py-3 text-zinc-300 transition hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Download PDF
        </button>
      </div>
    </div>
  );
}

export default DownloadReport;
